// Mocks generated by Mockito 5.4.6 from annotations
// in tjm_business_platform_logic/test/tjm_business_platform_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase/supabase.dart' as _i4;
import 'package:tjm_business_platform_logic/core/action_result.dart' as _i6;
import 'package:tjm_business_platform_logic/core/model/customer.dart' as _i10;
import 'package:tjm_business_platform_logic/core/model/expense.dart' as _i11;
import 'package:tjm_business_platform_logic/core/model/platform_user.dart'
    as _i7;
import 'package:tjm_business_platform_logic/core/model/report.dart' as _i9;
import 'package:tjm_business_platform_logic/data/auth_repository.dart' as _i3;
import 'package:tjm_business_platform_logic/data/data_repository.dart' as _i8;
import 'package:tjm_business_platform_logic/domain/auth.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuth_0 extends _i1.SmartFake implements _i2.Auth {
  _FakeAuth_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set client(_i4.SupabaseClient? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentUser(_i4.User? value) => super.noSuchMethod(
    Invocation.setter(#currentUser, value),
    returnValueForMissingStub: null,
  );

  @override
  void initSupabase(_i4.SupabaseClient? supabaseClient) => super.noSuchMethod(
    Invocation.method(#initSupabase, [supabaseClient]),
    returnValueForMissingStub: null,
  );

  @override
  bool isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<_i6.ActionResult> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i6.ActionResult> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i7.PlatformUser?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i5.Future<_i7.PlatformUser?>.value(),
          )
          as _i5.Future<_i7.PlatformUser?>);
}

/// A class which mocks [DataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataRepository extends _i1.Mock implements _i8.DataRepository {
  MockDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_0(this, Invocation.getter(#auth)),
          )
          as _i2.Auth);

  @override
  set client(_i4.SupabaseClient? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  set auth(_i2.Auth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  void initSupabase(_i4.SupabaseClient? supabaseClient) => super.noSuchMethod(
    Invocation.method(#initSupabase, [supabaseClient]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i9.Report>> getAllReports() =>
      (super.noSuchMethod(
            Invocation.method(#getAllReports, []),
            returnValue: _i5.Future<List<_i9.Report>>.value(<_i9.Report>[]),
          )
          as _i5.Future<List<_i9.Report>>);

  @override
  _i5.Future<List<_i10.Customer>> getAllCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCustomers, []),
            returnValue: _i5.Future<List<_i10.Customer>>.value(
              <_i10.Customer>[],
            ),
          )
          as _i5.Future<List<_i10.Customer>>);

  @override
  _i5.Future<List<_i11.Expense>> getAllExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExpenses, []),
            returnValue: _i5.Future<List<_i11.Expense>>.value(<_i11.Expense>[]),
          )
          as _i5.Future<List<_i11.Expense>>);

  @override
  _i5.Future<_i6.ActionResult> addNewCustomer(_i10.Customer? newCustomer) =>
      (super.noSuchMethod(
            Invocation.method(#addNewCustomer, [newCustomer]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i6.ActionResult> addNewReport(_i9.Report? newReport) =>
      (super.noSuchMethod(
            Invocation.method(#addNewReport, [newReport]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i6.ActionResult> addNewExpense(_i11.Expense? newExpense) =>
      (super.noSuchMethod(
            Invocation.method(#addNewExpense, [newExpense]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<List<String>> findCustomersByNameFragment(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#findCustomersByNameFragment, [name]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<_i6.ActionResult> deleteReport(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReport, [reportId]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i6.ActionResult> editCustomer(_i10.Customer? updatedCustomer) =>
      (super.noSuchMethod(
            Invocation.method(#editCustomer, [updatedCustomer]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<_i6.ActionResult> editReport(_i9.Report? updatedReport) =>
      (super.noSuchMethod(
            Invocation.method(#editReport, [updatedReport]),
            returnValue: _i5.Future<_i6.ActionResult>.value(
              _i6.ActionResult.ok,
            ),
          )
          as _i5.Future<_i6.ActionResult>);

  @override
  _i5.Future<double> getTotalIncome() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalIncome, []),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getTotalExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpenses, []),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getNetProfit() =>
      (super.noSuchMethod(
            Invocation.method(#getNetProfit, []),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);
}
